### ISSUE TITLE
代码不完整

### ISSUE THREAD

**Issue by heiducteam** [Wizzercn/MqttWk#1]
[INFO] mqttwk 1.0-SNAPSHOT ................................ SUCCESS [  0.284 s]
[INFO] wk-broker .......................................... FAILURE [  6.043 s]
[INFO] wk-test ............................................ SKIPPED
[INFO] wk-test-device-client .............................. SKIPPED
[INFO] wk-test-server-client 1.0-SNAPSHOT ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.064 s
[INFO] Finished at: 2018-07-03T15:52:29+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project wk-broker: Compilation failure: Compilation failure:
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[3,29] 找不到符号
[ERROR]   符号:   类 ConnectionDescriptor
[ERROR]   位置: 程序包 cn.wizzer.mqttwk.mqtt
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[4,29] 找不到符号
[ERROR]   符号:   类 ConnectionDescriptorStore
[ERROR]   位置: 程序包 cn.wizzer.mqttwk.mqtt
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[6,48] 找不到符号
[ERROR]   符号:   类 IConnectionsManager
[ERROR]   位置: 程序包 cn.wizzer.mqttwk.mqtt.common.connections
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[150,29] 找不到符号
[ERROR]   符号:   类 ConnectionDescriptor
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[108,9] 找不到符号
[ERROR]   符号:   类 ConnectionDescriptor
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[108,47] 找不到符号
[ERROR]   符号:   类 ConnectionDescriptor
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[109,15] 找不到符号
[ERROR]   符号:   类 ConnectionDescriptor
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[109,51] 找不到符号
[ERROR]   符号: 变量 connectionDescriptors
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[113,17] 找不到符号
[ERROR]   符号: 变量 connectionDescriptors
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[114,17] 找不到符号
[ERROR]   符号: 变量 connectionDescriptors
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[124,9] 找不到符号
[ERROR]   符号:   变量 m_interceptor
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[126,37] 找不到符号
[ERROR]   符号:   变量 SENDACK
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[126,46] 找不到符号
[ERROR]   符号:   变量 SESSION_CREATED
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[130,15] 找不到符号
[ERROR]   符号:   类 ClientSession
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[130,49] 找不到符号
[ERROR]   符号: 变量 sessionsRepository
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[138,26] 找不到符号
[ERROR]   符号:   变量 channel
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[140,56] 找不到符号
[ERROR]   符号:   变量 MESSAGES_REPUBLISHED
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[140,78] 找不到符号
[ERROR]   符号:   变量 ESTABLISHED
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[152,56] 找不到符号
[ERROR]   符号:   变量 DISCONNECTED
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[152,70] 找不到符号
[ERROR]   符号:   变量 SENDACK
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[158,9] 找不到符号
[ERROR]   符号:   类 ClientSession
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[158,43] 找不到符号
[ERROR]   符号: 变量 sessionsRepository
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[166,34] 找不到符号
[ERROR]   符号:   变量 mqttPacket
[ERROR]   位置: 类 cn.wizzer.mqttwk.mqtt.common.handler.MqttConnectHandler
[ERROR] /source/third/MqttWk/wk-broker/src/main/java/cn/wizzer/mqttwk/mqtt/common/handler/MqttConnectHandler.java:[171,21] 找不到符号
[ERROR]   符号: 变量 subscriptions
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :wk-broker

**Comment by Wizzercn** [comment]
对啊,没完工..

**Comment by Wizzercn** [comment]
@heiducteam 现在可以跑了，你试一下？:)
