### ISSUE TITLE
多机集群功能支持吗？

### ISSUE THREAD

**Issue by yzzh9** [Wizzercn/MqttWk#13]
集群功能有实现吗？对于集群中三台机器A、B、C，现在：
设备d1连接机器A并订阅topic：/a/+/c，
设备d2连接机器B并订阅topic：/a/b/#，
设备d3连接机器C并pub消息到topic：/a/b/c，设备d1、设备d2能收到消息吗？

看源码pub消息时只是在本机取出了符合条件的订阅topic，从而找出对应的session，再找出对应的channel进行下发，但不在本机的会话就不能下发了。

**Comment by Wizzercn** [comment]
支持集群（通过redis），但不支持+号，欢迎提交代码
