### ISSUE TITLE
设备断网，或杀掉进程，redis里的session和topic信息没有清理

### ISSUE THREAD

**Issue by Aarthas** [Wizzercn/MqttWk#14]
如题

**Comment by Aarthas** [comment]
因为channelInactive 里，idle的timeout 会被取消，不执行

**Comment by Wizzercn** [comment]
@Aarthas 不会清理的，否则重连后消息怎么下发呢

**Comment by Aarthas** [comment]
你好：

请问：那我怎么判断设备是否在线？是通过DefaultChannelGroup. find(ChannelId var1),找不到就是不在线这样判断吗？

场景：我上层应用要知道设备是否在线：
是否通过redis判断设备是否在线？如果不能，mqttwk需对外提供服务？

**Comment by Wizzercn** [comment]
@Aarthas https://github.com/Wizzercn/MqttWk/blob/netty/mqtt-broker/src/main/java/cn/wizzer/iot/mqtt/server/broker/webapi/WebApiController.java

**Comment by Aarthas** [comment]
明白了，谢谢

**Comment by Aarthas** [comment]
明白了，谢谢
