### ISSUE TITLE
启动报错是什么原因

### ISSUE THREAD

**Issue by minglang8632** [Wizzercn/MqttWk#2]
Plugin org.apache.maven.plugins:maven-install-plugin:2.4 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-install-plugin:jar:2.4: 1 problem was encountered while building the effective model
[ERROR] [FATAL] Non-parseable POM D:\01_java_tools\repository\org\apache\maven\plugins\maven-install-plugin\2.4\maven-install-plugin-2.4.pom: unexpected character in markup   (position: START_TAG seen ... function init() {\n          loaded += 1;\n\n          if (loaded < ... @44:24)  @ line 44, column 24
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

**Comment by wendal** [comment]
你本地文件有问题 D:\01_java_tools\repository\org\apache\maven\plugins\maven-install-plugin\2.4\maven-install-plugin-2.4.pom

删掉,重新来

**Comment by wendal** [comment]
使用方面的问题, 请到 https://nutz.cn 发帖
