### ISSUE TITLE
单例模式通配符订阅消息重复发送

### ISSUE THREAD

**Issue by BEWINDOWEB** [Wizzercn/MqttWk#4]
================ mqttwk =============
【发布】/topic1/1/1
【订阅收到】
/topic1/+/1 ：2条
/topic1/#：2条
================= moquette ============
【发布】/topic1/1/1
【订阅收到】
/topic1/+/1 ：1条
/topic1/#：1条

**Comment by Wizzercn** [comment]
暂不支持 + 号，可以自己修改实现，顺便提交 pull request 👍
