### ISSUE TITLE
web客户端

### ISSUE THREAD

**Issue by googlefan** [Wizzercn/MqttWk#8]
大神好，MqttWk 没有web端的管理平台么？我看wiki里是下载mqtt-spy。

**Comment by Wizzercn** [comment]
提供了web-api，没有界面（可以自己写），详见 https://github.com/Wizzercn/MqttWk/blob/netty/mqtt-broker/src/main/java/cn/wizzer/iot/mqtt/server/broker/webapi/WebApiController.java
